name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # hoặc 'master' nếu bạn dùng nhánh master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        run: yarn deploy
